name: Automated Testing

on: [ pull_request ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Composer Install
        run: composer install
      - name: Run Tests
        run: vendor/bin/phpunit
